name = "NFLTiebreaking"
uuid = "9e8a92f7-e673-4d92-ac92-678ee4e93ab7"
version = "0.1.0"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]

[workspace]
projects = ["test"]

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Chain = "1.0.0"
DataFrames = "1.8.1"
Logging = "1.11.0"
julia = "1.12"
