name = "NFLTiebreaking"
uuid = "9e8a92f7-e673-4d92-ac92-678ee4e93ab7"
version = "0.1.0"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]

[workspace]
projects = ["data", "test"]

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Arrow = "2.8.0"
Chain = "1.0.0"
DataFrames = "1.8.1"
Logging = "1.11.0"
Pkg = "1.12.1"
PrecompileTools = "1.3.3"
julia = "1.12"
